### ISSUE TITLE
Clarify headers implementation

### ISSUE THREAD

**Issue by theolampert** [superfly/fly#133]
I ran into a little bit of confusion regarding naming and uses of the fly 'headers' component while cross referencing with MDN docs. I understand you probably don't intend to support all methods that browsers support but it would be good to update the existing ones. For example, `getAll` is deprecated and `get` should now behave as `getAll` did. Another thing that tripped me up was the `toJSON` method which as far as I can tell doesn't actually return JSON but a normal javascript object. A subtle difference but enough to be confusing. I could look into this in a PR if it's something you'd you're interested in.

**Comment by mrkurt** [comment]
Yes! We really should match the web APIs unless there's a good reason not to. A PR would be delightful.

**Comment by michaeldwan** [comment]
@theolampert I was just bitten by this last week and went digging... turns out the MDN docs are somewhat misleading. [`get`](https://developer.mozilla.org/en-US/docs/Web/API/Headers/get) returns all values as a comma delimited string rather than an array of values as [`getAll`](https://developer.mozilla.org/en-US/docs/Web/API/Headers/getAll) did. 

```javascript
// before
headers.getAll("test") => ["first", "second"]
headers.get("test") => "first"

// after
headers.get("test") => "first,second"
```

Our current implementation of `get` follows this behavior, but we haven't yet removed `getAll` since working with an array is better than splitting a string. We'll rename `getAll` to something else soon to follow the deprecation in MDN without taking away a nice api.

As for `toJSON`, I can see the confusion. This function converts the class into primitive objects that could be serialized to json, but really are just merged into other headers during a fetch. It should probably be renamed to something else, but there's a few other places we use this convention so we'd need to take a look and make sure it's safe to change.

**Comment by theolampert** [comment]
@michaeldwan understood, I had trouble getting `getAll` to work for me at all. Basically I just ended up using `get` and `toJSON`.

**Comment by michaeldwan** [comment]
Oh dang. What was the problem?

**Comment by theolampert** [comment]
@michaeldwan actually scrap that, it does behave as expected. Feel free to close or change the title of the issue to something more specific.

**Comment by michaeldwan** [comment]
Cool thanks!
