### ISSUE TITLE
Apollo GraphQL + Caching

### ISSUE THREAD

**Issue by mrkurt** [superfly/fly#271]
A demonstration of Apollo GraphQL servers + Redis caching on Fly.

**Comment by mrkurt** [comment]
Done by @karlhughes: https://github.com/fly-examples/edge-graphql

**Comment by mrkurt** [comment]
We need to expand the readme on this a bit and make sure all these are addressed:

- [ ] what this application is (it’s a hello-world for graphql that uses redis to cache)
- [ ] why graphql is a good fit for edge applications
- [ ] caching and graphql, how graphql is a really good fit for caching but lots of people don’t do it because it’s perceived as hard to do, turns out not so much
- [ ] this whole application is just a docker container, you can build and run it locally to play with it, but it also loads trivially on Fly to run on a global edge network

**Comment by codepope** [comment]
* Overview
  * What is this, what does it demonstrate, what does it achieve, what does it enable

* Deploying to Fly
   * Speed run to getting it up and running, avoid distractions like local testing in readme
   * Don't forget to explain how to get an account from the command line (idea for flyctl - add first time run mode which asks if they have signed up)

* Running Graphql Queries
   * Include graphql queries as scripts in the repo so users don't cut and paste complex curls)

* What happens within the app
  * Broad stroke description of the processing involved in edge caching
  * Be explicit about what is being done for you (the caching process) without new code.


* What is Fly and Why Fly
  * Explainers for what Fly is with links to docs and other backgrounders
  * Explainer on how it enables edge caching

* Testing Latency
  * How to show the proof of performance
  * Again include scripts ready rolled
  * Also would note that all the script examples are hardwired for one book - might be an idea to offer some alternative values so that users can easily miss the cache and then test the follow up access time.


* Running Locally - not sure about this section at least until we have docker-compose support :)
