### ISSUE TITLE
Continuous deployment + [Various]

### ISSUE THREAD

**Issue by karllhughes** [superfly/fly#284]
I'm wondering if it's worth doing a series on deploying to Fly using various CI/CD providers? We don't have to hit all of them, but it seems like it would help customers overcome the barrier of figuring out how to use Fly with some of the most popular CI/CD tools.

Some that come to mind include:

- Travis
- CircleCI
- Buddy.works
- Codeship
- Github Actions

Let me know if this is interesting and I can start making issues for each.

**Comment by mrkurt** [comment]
I think these are (a) a great set of examples and (b) the best places for new contributors to start. So maybe instead of doing all of these, you could put together a skeleton + start issues for each? We were sort of talking about what app to use to demo these in #280.

(Also, CircleCI comes up a lot so that one's definitely worth doing).

**Comment by karllhughes** [comment]
Agreed.

I've got a few writers ready to write some articles in August, so I'm just getting a bunch of ideas fleshed out for them.

I'll create issues and update them accordingly. I like the idea of using the same demo app for all of them to maintain consistency and leave less to chance.
