### ISSUE TITLE
Less globals, more require/import on v8env

### ISSUE THREAD

**Issue by mrkurt** [superfly/fly#47]
The `fly.` global is sorta gross, it'd be much nicer to:

```javascript
import { Image } from 'fly/image'
```

The tricky part of this is that we build our base v8 context with webpack, and then build an app with webpack separately. So the app level webpack needs to understand how to import/require from that base webpack (or we need to do proper module loading).

**Comment by pudility** [comment]
I was playing around with different ways to import things from the fly namespace. Webpack was having some issues importing though, I think because it did not compile the v8env stuff. Another issue is getting the `ivm` and `dispatcher`. I think we should just be able to run `flyInit` and pass those to the index file and have it save them for when we need to export things - maybe something like this:
```JavaScript
export default function flyInit(ivm, dispatcher) {
  mcache = flyCacheInit(ivm, dispatcher)
  mhttp = require('./http')
  mlog = flyLogInit(ivm, dispatcher)
  mstreams = initStreams(ivm, dispatcher)
  mImage = initImage(ivm, dispatcher)

  return {
    cache: mcache,
    http: mhttp,
    log: mlog,
    streams: mstreams,
    Image: mImage
  }
}

export const cache = () => mcache
export const http = () => mhttp
export const log = () => mlog
export const streams = () => mstreams
export const Image = () => mImage
```
That however, still presents the same issue as above which is that the imports (eg. from `./ts/fly/image.ts`) still are not getting compiled by webpack so you get all sorts of errors. While this should work with the v8env, I am also not sure.

What are your thoughts?
