### ISSUE TITLE
Service Worker spec does not allow async event handlers

### ISSUE THREAD

**Issue by kentonv** [superfly/fly#8]
Hi there! I work on a similar implementation of the Service Worker spec at Cloudflare, and in looking at Fly we noticed that its FetchEvent handler behavior doesn't match the spec.

I'm not sure if Fly is aiming to be conformant with the Service Worker spec, so you should feel free to ignore this if not. In my view, though, it benefits all players in the broader "service worker ecosystem" if we all aim for conformance, because this enables developers to leverage this consistency to do more interesting things (e.g. write code that can seamlessly run on client or server depending on circumstances). Conversely, if Service Worker implementations develop a reputation for being subtly incompatible with each other, it may lead developers to become frustrated and disillusioned with the whole ecosystem.

Under the Service Workers spec, if a `FetchEvent` handler returns without calling `respondWith()`, then the request falls back to "default handling". In the case of a standard browser-side Service Worker -- which acts as a proxy -- this means the request continues on to the origin server as if no Service Worker existed. The event handler is not allowed to call respondWith() asynchronously -- once it has returned from the initial call, it has lost its chance.

From what I can tell, Fly is designed as an endpoint, not a proxy, and so it doesn't have a notion of an "origin server". So, there's seemingly no "default handling" to fall back to. But instead of returning some sort of error, it appears Fly permits the handler to call `respondWith()` later on, asynchronously (and if that doesn't happen, the request hangs forever). Many of Fly's examples seem to assume this ability (by using an async event handler function). These examples would not work in a standard Service Worker.

**Comment by jeromegn** [comment]
Hey there!

I wholeheartedly agree. We do aim at following the spec and hoped that people point out inconsistencies when they find some. So far we've only implemented part of the spec and the Web API. Mostly to fit some use cases we had. Our goal is to support as much as possible (when it makes sense, server-side.)

We are planning on implementing a superset of the spec when it makes sense too, i.e.: more `fetch` options, but more stuff under a different namespace. I think that will cause incompatibilities with normal in-browser Service Workers and Cloudflare. I'm not sure it matters though, I can hardly imagine a use case for running this on both a browser and an edge server.

Fly is designed as an endpoint, as you figured out. Full apps can be built without ever fetching from an origin. Users are responsible for handling a request and responding. The fallback is a very basic response with "standard" headers and a 200 OK status. You could think of our default response as the origin server. This is something that will be configurable eventually via this package.

For the issue at hand: It sounds like a fix for that would be to call `respondWith` with a `Promise` instead of allowing the event handler to return a `Promise`. I'll be implementing that shortly.

Thanks for opening this issue! Feel free to keep them coming, but this package will change a lot before `1.0.0` (or whenever it's considered stable anyway.) Until then, we'll be implementing more of the spec and fixing bits where we don't follow the spec.

**Comment by jeromegn** [comment]
Imperfect fix in 032c2ee, server will respond with a 500 and an error message if `FetchEvent.prototype.respondWith` has not been "entered" during the `"fetch"` event.

Closing for now. I was able to add a few more "failure" tests with this. Appreciated!

**Comment by kentonv** [comment]
Yep, we, too, expect to add some APIs outside the spec, and skip some APIs that are within the spec (e.g. CORS is totally unnecessary outside the browser). I guess the important thing is, where spec and implementation overlap, the behavior should match.

FWIW I do think it would be nice if event handlers could be async. Interested to know what @slightlyoff (service worker spec author) thinks.
